#!/bin/bash
set -e

MAJOR_NAME="rakest${MAJOR}"
LATEST_NAME="rakest"

EXEC_PATH="/opt/rake-standalone/${MAJOR}.${MINOR}/bin/rake"

/usr/bin/update-alternatives --remove ${MAJOR_NAME} ${EXEC_PATH}
/usr/bin/update-alternatives --remove ${LATEST_NAME} ${EXEC_PATH}
