#!/bin/bash
set -ex
docker build --pull -t rake-standalone-ubuntu-trusty-build build-image
docker run --rm -v $(pwd)/inside:/application:ro -v $(pwd)/out:/build -w /application rake-standalone-ubuntu-trusty-build /application/build-deb
