#!/bin/bash
set -ex
cd "${0%/*}"
../make-env.sh .
TEST_DISTRO="ubuntu:trusty"
BUILD_IMAGE="rake-standalone-ubuntu-trusty-build"

CONCATENATED=""
for x in $(cat ../env.list); do CONCATENATED="${CONCATENATED} --build-arg $x "; done

docker build ${CONCATENATED} --pull -t ${BUILD_IMAGE} build-image
rm -rf out

docker run --rm --env-file ./env.list.tmp -v $(pwd)/inside:/inside:ro -v $(pwd)/out:/out -w /inside ${BUILD_IMAGE} /inside/build-package

docker run --rm --env-file ./env.list.tmp -v $(pwd)/test:/test:ro -v $(pwd)/out:/out -w /test ${TEST_DISTRO} /test/test
