#!/bin/bash
set -e
[ -n "${RAKE_VERSION}" ]
dpkg -i /build/*.deb
apt-get -y -f install
apt-get -y install wget
cd /tmp
# TODO: set a variable for rake version and major/minor
wget https://github.com/ruby/rake/archive/v${RAKE_VERSION}.tar.gz
tar xvf v${RAKE_VERSION}.tar.gz
cd rake-${RAKE_VERSION}
ln -sf /usr/bin/rakest bin/rake
/opt/rake-standalone/1.0/bin/gem install hoe
rakest newb
