#!/bin/bash
set -ex
cd "${0%/*}"
DISTRO="precise"
docker build --pull -t rake-standalone-ubuntu-${DISTRO}-build build-image
rm -rf out
docker run --rm -v $(pwd)/inside:/application:ro -v $(pwd)/out:/build -w /application rake-standalone-ubuntu-${DISTRO}-build /application/build-deb
