#!/bin/bash
set -e
MAJOR=$(echo -n %{version} | cut -d "." -f 1)
MINOR=$(echo -n %{version} | cut -d "." -f 2)

MAJOR_NAME="rakest${MAJOR}"
LATEST_NAME="rakest"

EXEC_PATH="/opt/rake-standalone/${MAJOR}.${MINOR}/bin/rake"

/usr/sbin/update-alternatives --remove ${MAJOR_NAME} ${EXEC_PATH}
/usr/sbin/update-alternatives --remove ${LATEST_NAME} ${EXEC_PATH}
