#!/bin/bash
set -e
gpg --import /sign.key
[[ $(gpg --list-secret-keys) =~ uid(.*) ]]
KEYNAME="${BASH_REMATCH[1]}"
[ -n "${KEYNAME}" ] || { echo "could not find key for signing purpose"; exit 1; }
echo -e "%_gpg_name ${KEYNAME}\n%_signature gpg" > ${HOME}/.rpmmacros

cd /out
fpm -t rpm -s dir --rpm-sign -n rake-standalone-${MAJOR} --version "${MAJOR}.${MINOR}" --iteration ${BUILD_NUMBER} --after-install /inside/after-install --before-remove /inside/before-remove --provides rake-standalone -C / opt
chown -R --reference /inside/build-package .
