#!/bin/bash
set -ex
cd /out
fpm -t deb -s dir -n rake-standalone-${MAJOR} --version "${MAJOR}.${MINOR}" --iteration ${BUILD_NUMBER} --description "rake-standalone built from ${GIT_COMMIT}" \
    --after-install /inside/after-install --before-remove /inside/before-remove \
    --depends libgmp10 --provides rake-standalone -C / opt
chown -R --reference /inside/build-package .
