#!/bin/bash
set -ex
GPG_PRIVATE_KEY_FILE=$(readlink -f $1)
GPG_PUBLIC_KEY_FILE=$(readlink -f $2)
[ -r "${GPG_PRIVATE_KEY_FILE}" ] || { echo "missing private signature key file"; exit 1; }
[ -r "${GPG_PUBLIC_KEY_FILE}" ] || { echo "missing public signature key file"; exit 1; }

cd "${0%/*}"
../make-env.sh .
TEST_DISTRO="centos:7"
BUILD_IMAGE="rake-standalone-centos7-build"
CONCATENATED=""
for x in $(cat ../env.list); do CONCATENATED="${CONCATENATED} --build-arg $x "; done

docker build ${CONCATENATED} --pull -t ${BUILD_IMAGE} build-image
rm -rf out

docker run --rm --env-file ./env.list.tmp -v "${GPG_PRIVATE_KEY_FILE}":/sign.key:ro -v $(pwd)/inside:/inside:ro -v $(pwd)/out:/out -w /inside ${BUILD_IMAGE} /inside/build-package 

docker run --rm --env-file ./env.list.tmp -v ${GPG_PUBLIC_KEY_FILE}:/sign.pub:ro -v $(pwd)/test:/test:ro -v $(pwd)/out:/out -w /test ${TEST_DISTRO} /test/test
