#!/bin/bash
set -ex
cd "${0%/*}"
DISTRO="centos7"
TEST_DISTRO="centos:7"
docker build --pull -t rake-standalone-ubuntu-${DISTRO}-build build-image
rm -rf out
docker run --rm -v $(pwd)/inside:/application:ro -v $(pwd)/out:/build -w /application rake-standalone-ubuntu-${DISTRO}-build /application/build-rpm
docker run --rm -v $(pwd)/test:/test:ro -v $(pwd)/out:/build -w /test ${TEST_DISTRO} /test/test
