#!/bin/bash
set -ex
export BUILD_NUMBER="${BUILD_NUMBER:-0}"
export GIT_COMMIT="${GIT_COMMIT:-$(git rev-parse HEAD)}"
GPG_PRIVATE_KEY_FILE=$(readlink -f $1)
GPG_PUBLIC_KEY_FILE=$(readlink -f $2)
[ -r "${GPG_PRIVATE_KEY_FILE}" ] || { echo "missing private signature key file"; exit 1; }
[ -r "${GPG_PUBLIC_KEY_FILE}" ] || { echo "missing public signature key file"; exit 1; }
cd "${0%/*}"
TEST_IMAGE="rake-standalone-centos-6-test"
BUILD_IMAGE="rake-standalone-centos6-build"
CONCATENATED=""
for x in $(cat ../env.list); do CONCATENATED="${CONCATENATED} --build-arg $x "; done

docker build ${CONCATENATED} --pull -t ${BUILD_IMAGE} build-image
rm -rf out

docker run --rm -e "BUILD_NUMBER=${BUILD_NUMBER}" -e "GIT_COMMIT=${GIT_COMMIT}" --env-file ../env.list -v "${GPG_PRIVATE_KEY_FILE}":/sign.key:ro -v $(pwd)/inside:/inside:ro -v $(pwd)/out:/out -w /inside ${BUILD_IMAGE} /inside/build-package

docker build --pull -t ${TEST_IMAGE} test
docker run --rm --env-file ../env.list --rm -v $(pwd)/test:/test:ro  -v "${GPG_PUBLIC_KEY_FILE}":/sign.pub:ro -v $(pwd)/out:/out -w /test ${TEST_IMAGE} /test/test
