#!/bin/bash
set -ex
cd "${0%/*}"
TEST_IMAGE="rake-standalone-centos-6-test"
BUILD_IMAGE="rake-standalone-centos6-build"
CONCATENATED=""
for x in $(cat ../env.list); do CONCATENATED="${CONCATENATED} --build-arg $x "; done

docker build ${CONCATENATED} --pull -t ${BUILD_IMAGE} build-image
rm -rf out

docker run --env-file ../env.list --rm -v $(pwd)/inside:/inside:ro -v $(pwd)/out:/out -w /inside ${BUILD_IMAGE} /inside/build-package

docker build --pull -t ${TEST_IMAGE} test
docker run -e "BUILD_NUMBER=${BUILD_NUMBER:-0}" --env-file ../env.list --rm -v $(pwd)/test:/test:ro -v $(pwd)/out:/out -w /test ${TEST_IMAGE} /test/test
